packages:
  - 'apps/simeongriggs.dev'
  - 'apps/promptplaybook.dev'
  - 'apps/og'
  - 'apps/studio'
  - 'apps/functions/comment-telegram'
  - 'apps/functions/update-tints-readme'
  - 'apps/functions/format-code'
  - 'packages/sanity'
  - 'packages/constants'
  - 'packages/frontend'
  - 'packages/tailwind'
