packages:
  - 'apps/blog'
  - 'apps/playbook'
  - 'apps/og'
  - 'apps/studio'
  - 'apps/functions/comment-telegram'
  - 'apps/functions/update-tints-readme'
  - 'apps/functions/format-code'
  - 'packages/sanity'
  - 'packages/constants'
  - 'packages/tailwind'